### ISSUE TITLE
Lightgun | mame2016

### ISSUE THREAD

**Issue by Bboy486** [cosmo0/arcade-manager-data#26]
Do you csv for lightgun games on mame2106? I saw _controls-alternative: only "alternative" control schemes (rotary stick, keyboard, lightgun...) that are just not possible to use without dedicated controls_ but that looks to be in mame 2003.

I am trying to create a filter based on Sinden
https://docs.google.com/spreadsheets/d/e/2PACX-1vRJGpeos-AZoeveJK_ljasSbYa1x6Z2IkdUPqin2Q81z0POi8EGZiE8LkMZRx2r1YPHQ9sgGb9ZwSI5/pubhtml#

**Comment by cosmo0** [comment]
It's pretty easy to create your custom filter:

- go to http://adb.arcadeitalia.net/lista_mame.php?lang=en
- in "additional filters", add filters as you like (for your usage: "input" tab then "input" > "lightgun")
![image](https://user-images.githubusercontent.com/3973850/153892513-92fa6a31-6525-4bea-9fab-9d1c8e8a0264.png)

- in "options" click "export the results"
![image](https://user-images.githubusercontent.com/3973850/153892621-922587ee-0f58-4b22-a9a2-ef7dcdc1228b.png)

- in "format" select CSV, then in "version" make sure you're selecting the MAME version you're using
![image](https://user-images.githubusercontent.com/3973850/153892868-c4b1ebf1-d462-4f39-bd83-2e6de03bdb60.png)

Let me know if that works for you!
